services:
  frontend:
    image: krismos64/frontend:latest
    container_name: staka_frontend_prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: krismos64/backend:latest
    container_name: staka_backend_prod
    ports:
      - "3001:3001"
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: staka_db_prod
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=stakalivres
      - MYSQL_USER=staka
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /opt/staka/data/mysql:/var/lib/mysql
    restart: unless-stopped
