version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staka_app
    ports:
      - "3100:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/stakalivres
    depends_on:
      - db
    command: sh -c "npm install && npx prisma generate && npm run dev"

  db:
    image: mysql:8
    container_name: staka_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stakalivres
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
