version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staka_react_app
    ports:
      - "3100:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Si vous souhaitez ajouter une base de données plus tard,
  # décommentez la section ci-dessous :
  #
  # db:
  #   image: mysql:8
  #   container_name: staka_db
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: stakalivres
  #   volumes:
  #     - db_data:/var/lib/mysql
# volumes:
#   db_data:
