services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: staka_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:3001
      - DISPLAY=:99
      - DOCKER_ENV=true
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - ./shared:/app/shared
    depends_on:
      - backend
    restart: unless-stopped

  cypress:
    image: cypress/included:13.6.0
    container_name: staka_cypress
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    environment:
      - CYPRESS_baseUrl=http://host.docker.internal:3000
      - CYPRESS_video=false
      - CYPRESS_screenshotOnRunFailure=false
    depends_on:
      - db
      - backend
      - frontend
    command:
      [
        "npx",
        "cypress",
        "run",
        "--browser",
        "electron",
        "--headless",
        "--config-file",
        "cypress.config.cjs",
      ]
    profiles:
      - test

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: staka_backend
    ports:
      - "3001:3001"
      - "5555:5555"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: staka_db
    command: --mysql-native-password=ON
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stakalivres
      - MYSQL_USER=staka
      - MYSQL_PASSWORD=staka
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
