services:
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: staka_frontend
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: staka_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./shared:/app/shared
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: staka_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stakalivres
      - MYSQL_USER=staka
      - MYSQL_PASSWORD=staka
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: