# syntax=docker/dockerfile:1.6
FROM node:20.19.0-slim

# Installer OpenSSL et curl pour les healthchecks
RUN apt-get update && \
    apt-get install -y curl openssl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copier les package.json et le schema Prisma
COPY backend/package*.json ./
COPY backend/prisma ./prisma

# Installer les dépendances
RUN npm install --legacy-peer-deps --omit=optional

# Générer Prisma Client
RUN npx prisma generate

# Copier le reste du code source
COPY backend/. ./

WORKDIR /app

EXPOSE 3001

# Mode développement avec nodemon
CMD ["npm", "run", "dev"]