-- AlterTable
ALTER TABLE `commandes` ADD COLUMN `packType` VARCHAR(100) NULL,
    ADD COLUMN `pagesDeclarees` INTEGER NULL,
    ADD COLUMN `pagesVerifiees` INTEGER NULL,
    ADD COLUMN `prixEstime` INTEGER NULL,
    ADD COLUMN `prixFinal` INTEGER NULL,
    MODIFY `statut` ENUM('EN_ATTENTE', 'EN_ATTENTE_VERIFICATION', 'EN_ATTENTE_CONSULTATION', 'ESTIMATION_ENVOYEE', 'PAYEE', 'EN_COURS', 'TERMINE', 'ANNULEE', 'SUSPENDUE') NOT NULL DEFAULT 'EN_ATTENTE';

-- AlterTable
ALTER TABLE `pending_commandes` ADD COLUMN `nombrePages` INTEGER NULL;
